### ISSUE TITLE
Error when executing SPEAR, even using test files

### ISSUE THREAD

**Issue by AndreaAguadoM** [m-crown/SPEAR#43]
Hello! I am trying to use spear using some of my vcf files as input and I am obtaining the following error: 
Error in rule summarise_vcfs:
    jobid: 1
    output: spear_output/spear_annotation_summary.tsv, spear_output/spear_score_summary.tsv
    log: spear_output/intermediate_output/logs/summarise/summary.log (check log file(s) for error message)
    shell:
        echo "BA.2.12.1 BA.5.3.1" > spear_output/intermediate_output/sample_list.txt ; for i in $(find spear_output/final_vcfs/ -type f -exec grep -lP '^NC_045512\.2' {} \;) ; do BNAME=${i##*/}; BNAME2=${BNAME%.spear.vcf}; grep -v '^#' "$i" | sed "s|^NC_045512\.2|$BNAME2|g"; done > spear_output/intermediate_output/anno_concat.tsv 2> spear_output/intermediate_output/logs/summarise/summary.log ; convert_format.py --is_vcf_input True --is_filtered False --per_sample_outputs False spear_output/intermediate_output/anno_concat.tsv spear_output /root/mambaforge/envs/spear/data spear_output/all_samples.spear.vcf spear_output/intermediate_output/sample_list.txt 2> spear_output/intermediate_output/logs/summarise/summary.log 
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

This happens with my vcf files but also with the BA.2.12.1.vcf and BA.5.3.1.vcf files available in this repository, so I think my files are not the problem. 

Could someone help me? This happens when trying to use the vcf mode of the spear tool. 

The content of the error log file is the following: 

Traceback (most recent call last):
  File "/root/mambaforge/envs/spear/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'BEC_EF_sample'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/mambaforge/envs/spear/bin/convert_format.py", line 347, in <module>
    main()
  File "/root/mambaforge/envs/spear/bin/convert_format.py", line 320, in main
    score_subset[score] = score_subset[score].astype(float)
  File "/root/mambaforge/envs/spear/lib/python3.10/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/root/mambaforge/envs/spear/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'BEC_EF_sample'

Thanks in advance!

**Comment by m-crown** [comment]
Hi looking into this now

**Comment by m-crown** [comment]
I have just pushed a commit that should fix this issue - please let me know if it works for you.

**Comment by m-crown** [comment]
Marking as resolved.
